
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_LINE = 13;
  public static final int MENOR = 2;
  public static final int PUNTO = 9;
  public static final int CADENA = 18;
  public static final int FINCADENA = 15;
  public static final int TK_SYSTEM = 11;
  public static final int COMA = 16;
  public static final int TK_CONCAT = 14;
  public static final int ENTEROS = 17;
  public static final int MAYOR = 3;
  public static final int EOF = 0;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int PAR2 = 7;
  public static final int LLAVE2 = 5;
  public static final int PAR1 = 6;
  public static final int LLAVE1 = 4;
  public static final int TK_EJEMPLO = 10;
  public static final int TK_PRINT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR",
  "MAYOR",
  "LLAVE1",
  "LLAVE2",
  "PAR1",
  "PAR2",
  "DIV",
  "PUNTO",
  "TK_EJEMPLO",
  "TK_SYSTEM",
  "TK_PRINT",
  "TK_LINE",
  "TK_CONCAT",
  "FINCADENA",
  "COMA",
  "ENTEROS",
  "CADENA"
  };
}

