
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 16;
  public static final int TKROUND = 8;
  public static final int CADENA = 2;
  public static final int FINCADENA = 6;
  public static final int TKEVALUAR = 9;
  public static final int TKLENGTH = 10;
  public static final int UMENOS = 17;
  public static final int NUMEROS = 3;
  public static final int EOF = 0;
  public static final int MULT = 11;
  public static final int DIV = 12;
  public static final int error = 1;
  public static final int PAR2 = 14;
  public static final int LLAVE2 = 5;
  public static final int PAR1 = 13;
  public static final int LLAVE1 = 4;
  public static final int TKIMP = 7;
  public static final int MAS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "NUMEROS",
  "LLAVE1",
  "LLAVE2",
  "FINCADENA",
  "TKIMP",
  "TKROUND",
  "TKEVALUAR",
  "TKLENGTH",
  "MULT",
  "DIV",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS"
  };
}

